const ROLES = Object.freeze({
  ADMIN: "admin",
  PATWARI: "patwari",
  TEHSILDAR: "tehsildar",
  DC: "dc",
});

const LAND_STATUSES = Object.freeze([
  "Pending",
  "Verified",
  "Registered",
  "Rejected",
  "TransferPending",
  "Disputed",
]);

const DISPUTE_STATUSES = Object.freeze([
  "Filed",
  "UnderReview",
  "Resolved",
  "Rejected",
]);

const AUDIT_ACTIONS = Object.freeze({
  LAND_REGISTERED: "LAND_REGISTERED",
  LAND_VERIFIED: "LAND_VERIFIED",
  LAND_APPROVED: "LAND_APPROVED",
  LAND_REJECTED: "LAND_REJECTED",
  TRANSFER_INITIATED: "TRANSFER_INITIATED",
  TRANSFER_APPROVED: "TRANSFER_APPROVED",
  TRANSFER_REJECTED: "TRANSFER_REJECTED",
  DISPUTE_FILED: "DISPUTE_FILED",
  DISPUTE_REVIEWED: "DISPUTE_REVIEWED",
  DISPUTE_RESOLVED: "DISPUTE_RESOLVED",
  DISPUTE_REJECTED: "DISPUTE_REJECTED",
  OFFICER_CREATED: "OFFICER_CREATED",
  OFFICER_DEACTIVATED: "OFFICER_DEACTIVATED",
  OFFICER_ACTIVATED: "OFFICER_ACTIVATED",
  OFFICER_LOGIN: "OFFICER_LOGIN",
  OFFICER_LOGOUT: "OFFICER_LOGOUT",
  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
  PROFILE_UPDATED: "PROFILE_UPDATED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
});

module.exports = {
  ROLES,
  LAND_STATUSES,
  DISPUTE_STATUSES,
  AUDIT_ACTIONS,
};
