const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("\n+------------------------------------------+");
  console.log("¦   BLRS Smart Contract Deployment         ¦");
  console.log("¦   Network: Hardhat Local                 ¦");
  console.log("+------------------------------------------+\n");

  const [deployer, patwari, tehsildar, dc] = await ethers.getSigners();

  console.log("Deployment Account:", deployer.address);
  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("Account Balance:", ethers.formatEther(balance), "ETH\n");

  console.log("Deploying RoleManager...");
  const RoleManager = await ethers.getContractFactory("RoleManager");
  const roleManager = await RoleManager.deploy(deployer.address);
  await roleManager.waitForDeployment();
  const rmAddress = await roleManager.getAddress();
  console.log("RoleManager:", rmAddress);

  console.log("\nDeploying LandRegistry...");
  const LandRegistry = await ethers.getContractFactory("LandRegistry");
  const landRegistry = await LandRegistry.deploy(rmAddress);
  await landRegistry.waitForDeployment();
  const lrAddress = await landRegistry.getAddress();
  console.log("LandRegistry:", lrAddress);

  console.log("\nDeploying DisputeResolution...");
  const DisputeResolution = await ethers.getContractFactory("DisputeResolution");
  const disputeResolution = await DisputeResolution.deploy(rmAddress, lrAddress);
  await disputeResolution.waitForDeployment();
  const drAddress = await disputeResolution.getAddress();
  console.log("DisputeResolution:", drAddress);

  console.log("\nDeploying LandToken...");
  const LandToken = await ethers.getContractFactory("LandToken");
  const landToken = await LandToken.deploy(rmAddress);
  await landToken.waitForDeployment();
  const ltAddress = await landToken.getAddress();
  console.log("LandToken:", ltAddress);

  console.log("\nConfiguring LandRegistry ownership for dispute workflow...");
  const transferOwnerTx = await landRegistry.transferOwnership(drAddress);
  await transferOwnerTx.wait();
  console.log("Ownership set to DisputeResolution");

  console.log("\nAdding test officers...");
  const PATWARI_ROLE = await roleManager.PATWARI_ROLE();
  const TEHSILDAR_ROLE = await roleManager.TEHSILDAR_ROLE();
  const DC_ROLE = await roleManager.DC_ROLE();

  await (await roleManager.addOfficer(
    patwari.address,
    "Muhammad Ayaz Khan",
    "5430100000002",
    "patwari.quetta@blrs.gov.pk",
    "Quetta",
    PATWARI_ROLE
  )).wait();

  await (await roleManager.addOfficer(
    tehsildar.address,
    "Abdul Qadir Mengal",
    "5430100000003",
    "tehsildar.quetta@blrs.gov.pk",
    "Quetta",
    TEHSILDAR_ROLE
  )).wait();

  await (await roleManager.addOfficer(
    dc.address,
    "Sardar Ahmed Raisani",
    "5430100000004",
    "dc.quetta@blrs.gov.pk",
    "Quetta",
    DC_ROLE
  )).wait();

  const deploymentData = {
    network: "localhost",
    chainId: 31337,
    deployedAt: new Date().toISOString(),
    deployer: deployer.address,
    contracts: {
      RoleManager: rmAddress,
      LandRegistry: lrAddress,
      DisputeResolution: drAddress,
      LandToken: ltAddress,
    },
    testAccounts: {
      admin: deployer.address,
      patwari: patwari.address,
      tehsildar: tehsildar.address,
      dc: dc.address,
    },
  };

  const outputDir = path.join(__dirname, "../deployments");
  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

  fs.writeFileSync(
    path.join(outputDir, "localhost.json"),
    JSON.stringify(deploymentData, null, 2)
  );

  const envContent = `# Auto-generated by deploy.js on ${new Date().toISOString()}
ROLE_MANAGER_ADDRESS=${rmAddress}
LAND_REGISTRY_ADDRESS=${lrAddress}
DISPUTE_RESOLUTION_ADDRESS=${drAddress}
LAND_TOKEN_ADDRESS=${ltAddress}
DEPLOYER_ADDRESS=${deployer.address}
PATWARI_ADDRESS=${patwari.address}
TEHSILDAR_ADDRESS=${tehsildar.address}
DC_ADDRESS=${dc.address}
`;

  fs.writeFileSync(path.join(outputDir, "localhost.env"), envContent);

  console.log("\nDeployment complete");
  console.log("Saved:", path.join(outputDir, "localhost.json"));
  console.log("Saved:", path.join(outputDir, "localhost.env"));
}

main().catch((error) => {
  console.error("Deployment failed:", error);
  process.exit(1);
});