const { ethers } = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("\n+------------------------------------------+");
  console.log("¦   BLRS Smart Contract Deployment         ¦");
  console.log("¦   Network: Polygon Amoy Testnet          ¦");
  console.log("+------------------------------------------+\n");

  const [deployer] = await ethers.getSigners();

  console.log("Deployment Account:", deployer.address);
  const balance = await ethers.provider.getBalance(deployer.address);
  const formatted = ethers.formatEther(balance);
  console.log("Account Balance:", formatted, "MATIC");

  if (parseFloat(formatted) < 0.1) {
    console.error("\nInsufficient MATIC balance.");
    console.log("Get test MATIC at https://faucet.polygon.technology/");
    process.exit(1);
  }

  console.log("\nDeploying to public testnet...\n");

  const RoleManager = await ethers.getContractFactory("RoleManager");
  const roleManager = await RoleManager.deploy(deployer.address);
  await roleManager.waitForDeployment();
  const rmAddress = await roleManager.getAddress();

  const LandRegistry = await ethers.getContractFactory("LandRegistry");
  const landRegistry = await LandRegistry.deploy(rmAddress);
  await landRegistry.waitForDeployment();
  const lrAddress = await landRegistry.getAddress();

  const DisputeResolution = await ethers.getContractFactory("DisputeResolution");
  const disputeResolution = await DisputeResolution.deploy(rmAddress, lrAddress);
  await disputeResolution.waitForDeployment();
  const drAddress = await disputeResolution.getAddress();

  const LandToken = await ethers.getContractFactory("LandToken");
  const landToken = await LandToken.deploy(rmAddress);
  await landToken.waitForDeployment();
  const ltAddress = await landToken.getAddress();

  await (await landRegistry.transferOwnership(drAddress)).wait();

  const deploymentData = {
    network: "amoy",
    chainId: 80002,
    deployedAt: new Date().toISOString(),
    deployer: deployer.address,
    polygonscan: "https://amoy.polygonscan.com",
    contracts: {
      RoleManager: {
        address: rmAddress,
        url: `https://amoy.polygonscan.com/address/${rmAddress}`,
      },
      LandRegistry: {
        address: lrAddress,
        url: `https://amoy.polygonscan.com/address/${lrAddress}`,
      },
      DisputeResolution: {
        address: drAddress,
        url: `https://amoy.polygonscan.com/address/${drAddress}`,
      },
      LandToken: {
        address: ltAddress,
        url: `https://amoy.polygonscan.com/address/${ltAddress}`,
      },
    },
  };

  const outputDir = path.join(__dirname, "../deployments");
  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

  fs.writeFileSync(
    path.join(outputDir, "amoy.json"),
    JSON.stringify(deploymentData, null, 2)
  );

  const envContent = `# Auto-generated by deployAmoy.js - Polygon Amoy Testnet
BLOCKCHAIN_NETWORK=amoy
CHAIN_ID=80002
RPC_URL=https://rpc-amoy.polygon.technology/
ROLE_MANAGER_ADDRESS=${rmAddress}
LAND_REGISTRY_ADDRESS=${lrAddress}
DISPUTE_RESOLUTION_ADDRESS=${drAddress}
LAND_TOKEN_ADDRESS=${ltAddress}
`;

  fs.writeFileSync(path.join(outputDir, "amoy.env"), envContent);

  console.log("\nAmoy deployment complete\n");
  console.log(`RoleManager: https://amoy.polygonscan.com/address/${rmAddress}`);
  console.log(`LandRegistry: https://amoy.polygonscan.com/address/${lrAddress}`);
  console.log(`DisputeResolution: https://amoy.polygonscan.com/address/${drAddress}`);
  console.log(`LandToken: https://amoy.polygonscan.com/address/${ltAddress}`);
}

main().catch((error) => {
  console.error("Amoy deployment failed:", error);
  process.exit(1);
});